### PR TITLE
Support for quotes, plus  auto-resize of editor with wysihtml5_size_matters

### PR DESCRIPTION
**Pull request by x00**
Support for quotes, plus  auto-resize of editor with wysihtml5_size_matters

### CODE REVIEW

**Comment by x00** [comment]
I had some issues with bower, so may need to check all the depedences are included in the concat

**Comment by kasperisager** [comment]
Thanks a ton for the PR! If you can squash everything together I'll have it merged ASAP.

**Comment by x00** [comment]
I can do another pull request if you want the minified file.

**Comment by kasperisager** [comment]
...as in squashing the commits: http://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Squashing-Commits

**Comment by x00** [comment]
no worries

**Comment by x00** [comment]
done

**Comment by kasperisager** [comment]
Beauty :+1: Thanks!

**Pull request merged**
